### ISSUE TITLE
How to verify read_state request

### ISSUE THREAD

**Issue by hewm** [dfinity/response-verification#193]
``When the request and response header parameters are

`
code：200

request_headers:  [('User-Agent', 'python-requests/2.31.0'), ('Accept-Encoding', 'gzip, deflate'), ('Accept', '*/*'), ('Connection', 'keep-alive'), ('Content-Type', 'application/cbor'), ('Content-Length', '335')]

response_headers:  [('Server', 'nginx/1.21.3'), ('Date', 'Wed, 11 Aug 2023 12:06:57 GMT'), ('Content-Type', 'application/cbor, application/cbor'), ('Content-Length', '761'), ('Connection', 'keep-alive'), ('X-Request-ID', 'b0cac601-1303-24f4-04f1-f62cr51ac111'), ('Access-Control-Allow-Origin', '*'), ('Access-Control-Allow-Methods', 'HEAD, POST'), ('Access-Control-Allow-Headers', 'DNT,User-Agent,X-Requested-With,If-None-Match,If-Modified-Since,Cache-Control,Content-Type,Range,Cookie'), ('Access-Control-Expose-Headers', 'Accept-Ranges,Content-Length,Content-Range'), ('Access-Control-Max-Age', '600'), ('X-Content-Type-Options', 'nosniff')]
`

The verification result is
`CertificationResult { passed: false, response: None, verification_version: 1 }`

**Comment by nathanosdev** [comment]
Similar to https://github.com/dfinity/response-verification/issues/192, I'm closing since this is not the intended purpose of this library, https://github.com/dfinity/agent-rs is responsible for validating read_state calls. Please feel free to open a thread on the https://forum.dfinity.org/ if there's further questions.
